spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ #database
    username: #username
    password: #password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 371326339584-3rpcdc3flchk3geusd0skrau6it2dip7.apps.googleusercontent.com
            client-secret: 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
server:
  port: 8080
  # Configurations for Okta/google/GitHub
okta:
  oauth2:
    issuer: https://dev-89351563.okta.com/oauth2/default
    client-id: 0oalge2s8iuMghBz45d7
    client-secret: fXRLh6cBbkqv1b-N4To_CeMeinq_u6SoQJc0oOSvvthymgF7l-_GPl_bUfgEM
  


