server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telecom_billing_service?useSSL=false
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  application:
    name: billing-service
