spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CNKart
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update