spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CNPayment
    username: root
    password: sprootpassword
    driver-class: com.mysql.cj.jdbc.Driver

  jpa:
    properties.hibernate-dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate.globally_quoted_identifiers: true

