server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telecom_support_service?useSSL=false
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: support-service
